package pro.komdosh.searchablerestentity;

import lombok.Data;

import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

@Data
public final class EntityScope {

    private static final String COMMENT = "Generated by SearchableRestEntity";
    private ZonedDateTime date;
    private String packageName;
    private String entity;
    private String entityName;
    private String path;

    EntityScope(String packageName, String sourceClassName, String path) {
        this.date = ZonedDateTime.now();
        this.packageName = packageName;
        this.entity = sourceClassName;
        this.entityName = sourceClassName.split("Entity")[0];
        if (path == null || "".equals(path)) {
            this.path = "/api/v1/" + getEntityNameStartLowerCase();
        } else {
            this.path = path;
        }
    }

    public String getComment() {
        return COMMENT;
    }

    public String getDate() {
        return date.format(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
    }


    public String getEntityDto() {
        return entityName + "Dto";
    }

    public String getEntityService() {
        return entityName + "Service";
    }

    public String getSourceClassNameWithPackage() {
        return packageName + "." + entity;
    }

    public String getEntityNameStartLowerCase() {
        return entityName.substring(0, 1).toLowerCase() + entityName.substring(1);
    }

    public String getRepositoryClassNameWithPackage() {
        return packageName + "." + entityName + "Repository";
    }

    public String getControllerClassNameWithPackage() {
        return packageName + "." + entityName + "Controller";
    }

    public String getEntityDtoClassNameWithPackage() {
        return packageName + "." + getEntityDto();
    }

    public String getEntityServiceClassNameWithPackage() {
        return packageName + "." + getEntityService();
    }

    public String getEntityMapperClassNameWithPackage() {
        return packageName + "." + entityName + "Mapper";
    }
}
